### PR TITLE
Danish translation

### PR DESCRIPTION
**Pull request by emmilinette**
With @Alkarex

### CODE REVIEW

**Comment by Deevad** [comment]
Thanks to both of you ! I'll render and upload within the next 10 minutes

**Comment by Alkarex** [comment]
No pressure, but it does not look like that the Danish version of Episode 8 is online yet
https://www.peppercarrot.com/da/article285/episode-8-pepper-s-birthday-party

**Comment by Deevad** [comment]
Thank you @Alkarex  ; mini hicup on my side, the script was asking me in background to confirm a minor overwrite for doing the upload ( I added a FTP rule to hide future episode 22 , I'll upload the alpha of ep22 today on Github, french version with artwork still in pencil ). It's uploading now all the fix for ep07 and the translation for ep08.

**Comment by Alkarex** [comment]
Super :-)
I do not think we will be able to translate all the episodes 9-22 before 22 is ready :-P
Small rendering bug in the daemons book in Episode 8; I will try to fix it tonight.

**Pull request merged**
